// Generated by CoffeeScript 1.4.0

/*
AutoReadme v0.0.1
http://jsliang.github.com/AutoReadme

Copyright (c) 2013, Jui-Shan Liang <jenny@jsliang.com>
All rights reserved.
Licensed under GPL v2.
*/


(function() {
  var $;

  $ = jQuery;

  $(document).ready(function() {
    var converter, env, tmpl;
    converter = new Showdown.converter();
    env = new nunjucks.Environment();
    tmpl = new nunjucks.Template('<p>DEFAULT!</p> {{ contents }}');
    return $.getGithubFileByFilePath("jsliang", "sublime-pelican", "README.md", function(contents) {
      var templ_variables;
      templ_variables = {
        contents: converter.makeHtml(contents)
      };
      $("body").html(tmpl.render(templ_variables));
      return $(document).attr('title', $("h1:first").text());
    });
  });

}).call(this);
